// shim.js — runs in the page's main world. Wraps navigator.getGamepads() so
// controllers streamed by the Finally the Controller Works app appear as
// standard-mapping gamepads alongside any real ones, fires
// gamepadconnected/gamepaddisconnected, and forwards vibrationActuator effects.
(() => {
  if (navigator.__ftcwBridge) return;
  const NINTENDO_LABELS = false;
  const PERSONA_DEFAULT = 'nintendo';
  const PERSONA = (() => { try { const v = localStorage.getItem('ftcwPersona'); if (v === 'xbox' || v === 'nintendo') return v; } catch {} return PERSONA_DEFAULT; })();
  const EXTRA_BUTTONS = false;
  const BIT = { y:1<<0,x:1<<1,b:1<<2,a:1<<3,r:1<<6,zr:1<<7,minus:1<<8,plus:1<<9,rStick:1<<10,lStick:1<<11,home:1<<12,capture:1<<13,c:1<<14,dpadDown:1<<16,dpadUp:1<<17,dpadRight:1<<18,dpadLeft:1<<19,l:1<<22,zl:1<<23,gr:1<<24,gl:1<<25 };
  const face=NINTENDO_LABELS?[BIT.a,BIT.b,BIT.x,BIT.y]:[BIT.b,BIT.a,BIT.y,BIT.x];
  const BUTTON_BITS=[face[0],face[1],face[2],face[3],BIT.l,BIT.r,0,0,BIT.minus,BIT.plus,BIT.lStick,BIT.rStick,BIT.dpadUp,BIT.dpadDown,BIT.dpadLeft,BIT.dpadRight,BIT.home,BIT.capture,...(EXTRA_BUTTONS?[BIT.c,BIT.gl,BIT.gr]:[])];
  const BUTTON_COUNT=BUTTON_BITS.length;
  const pads=new Map(); const nativeGetGamepads=Navigator.prototype.getGamepads; let bridgeUp=false;
  const toApp=(obj)=>document.dispatchEvent(new CustomEvent('ftcw-up',{detail:JSON.stringify(obj)}));
  const rumbleToApp=(slot,strong,weak,phase)=>toApp({t:'rumble',slot,strong,weak,phase});
  const STATS_WINDOW_MS=5000; let arrivals=new Map(),getCalls=0,statsTimer=null;
  function noteArrival(slot){let a=arrivals.get(slot);if(!a){a=[];arrivals.set(slot,a);}a.push(performance.now());if(statsTimer===null)statsTimer=setTimeout(flushStats,STATS_WINDOW_MS);}
  function flushStats(){statsTimer=null;for(const[slot,a]of arrivals){const gaps=[];for(let i=1;i<a.length;i++)gaps.push(a[i]-a[i-1]);gaps.sort((x,y)=>x-y);const q=(f)=>gaps.length?+gaps[Math.min(gaps.length-1,Math.floor(gaps.length*f))].toFixed(1):0;toApp({t:'stats',slot,win:STATS_WINDOW_MS,n:a.length,med:q(.5),p95:q(.95),max:gaps.length?+gaps[gaps.length-1].toFixed(1):0,over60:gaps.filter(g=>g>60).length,gets:getCalls,hidden:document.hidden,url:location.host});}arrivals=new Map();getCalls=0;}
  function makeActuator(slot){let timer=null,refresh=null,pending=null,generation=0,actuator;const current=()=>bridgeUp&&pads.get(slot)?.vibrationActuator===actuator;const finish=(r)=>{if(pending){const x=pending;pending=null;x(r);}};const stop=(r='preempted')=>{generation++;if(timer!==null)clearTimeout(timer);if(refresh!==null)clearInterval(refresh);timer=refresh=null;if(current())rumbleToApp(slot,0,0,'stop');finish(r);};actuator={type:'dual-rumble',effects:['dual-rumble'],playEffect(type,params={}){if(type!=='dual-rumble')return Promise.resolve('invalid-parameter');if(!current())return Promise.resolve('preempted');const duration=Number(params.duration??0),delay=Number(params.startDelay??0);if(!Number.isFinite(duration)||!Number.isFinite(delay)||duration<0||delay<0||duration>60000||delay>60000)return Promise.resolve('invalid-parameter');const strong=clamp01(params.strongMagnitude),weak=clamp01(params.weakMagnitude);stop();const owner=generation;return new Promise(resolve=>{pending=resolve;const pulse=(phase='refresh')=>{if(owner!==generation||!current()){stop();return;}rumbleToApp(slot,strong,weak,phase);};const start=()=>{if(owner!==generation||!current()){stop();return;}pulse('start');refresh=setInterval(pulse,200);timer=setTimeout(()=>stop('complete'),duration);};if(delay>0)timer=setTimeout(start,delay);else start();});},reset(){stop();return Promise.resolve('complete');},stop};return actuator;}
  const clamp01=(v)=>Math.min(1,Math.max(0,Number(v)||0));
  const padId=(model,name)=>PERSONA==='xbox'?'Xbox Wireless Controller (STANDARD GAMEPAD Vendor: 045e Product: 0b13)':`${name||model} (STANDARD GAMEPAD Vendor: 057e Product: 2069)`;
  function makePad(slot,model,name){const buttons=[];for(let i=0;i<BUTTON_COUNT;i++){const b={pressed:false,touched:false,value:0};if(typeof GamepadButton!=='undefined')Object.setPrototypeOf(b,GamepadButton.prototype);buttons.push(b);}const pad={id:padId(model,name),index:-1,connected:true,mapping:'standard',timestamp:performance.now(),axes:[0,0,0,0],buttons,hapticActuators:[],vibrationActuator:makeActuator(slot),__ftcwSlot:slot};if(typeof Gamepad!=='undefined')Object.setPrototypeOf(pad,Gamepad.prototype);return pad;}
  function assignIndex(pad){const taken=new Set();for(const g of nativeGetGamepads.call(navigator))if(g)taken.add(g.index);for(const p of pads.values())if(p!==pad&&p.index>=0)taken.add(p.index);let i=0;while(taken.has(i))i++;pad.index=i;}
  function fire(type,pad){const ev=new Event(type);Object.defineProperty(ev,'gamepad',{value:pad,enumerable:true});window.dispatchEvent(ev);}
  function applyState(pad,m){const b=m.b>>>0,btn=pad.buttons;for(let i=0;i<BUTTON_COUNT;i++){const bit=BUTTON_BITS[i];if(!bit)continue;const on=(b&bit)!==0;btn[i].pressed=on;btn[i].touched=on;btn[i].value=on?1:0;}const lt=Math.max((b&BIT.zl)?1:0,(m.lt||0)/255),rt=Math.max((b&BIT.zr)?1:0,(m.rt||0)/255);btn[6].value=lt;btn[6].pressed=lt>.5;btn[6].touched=lt>0;btn[7].value=rt;btn[7].pressed=rt>.5;btn[7].touched=rt>0;pad.axes[0]=m.lx;pad.axes[1]=-m.ly;pad.axes[2]=m.rx;pad.axes[3]=-m.ry;pad.timestamp=performance.now();}
  function disconnectAll(){for(const[slot,pad]of pads){pads.delete(slot);pad.connected=false;pad.vibrationActuator.stop();fire('gamepaddisconnected',pad);}}
  document.addEventListener('ftcw-bridge',(ev)=>{let m;try{m=JSON.parse(ev.detail);}catch{return;}switch(m.t){case'bridge':bridgeUp=!!m.up;if(!bridgeUp)disconnectAll();break;case'connected':{let pad=pads.get(m.slot);if(pad){pad.id=padId(m.model,m.name);break;}pad=makePad(m.slot,m.model,m.name);assignIndex(pad);pads.set(m.slot,pad);fire('gamepadconnected',pad);break;}case'name':{const pad=pads.get(m.slot);if(pad)pad.id=padId('',m.name);break;}case'state':{const pad=pads.get(m.slot);if(pad){applyState(pad,m);noteArrival(m.slot);}break;}case'disconnected':{const pad=pads.get(m.slot);if(!pad)break;pads.delete(m.slot);pad.connected=false;pad.vibrationActuator.stop();fire('gamepaddisconnected',pad);break;}}});
  function snapshot(pad){const copy={id:pad.id,index:pad.index,connected:pad.connected,mapping:pad.mapping,timestamp:pad.timestamp,axes:pad.axes.slice(),buttons:pad.buttons.map(b=>{const x={pressed:b.pressed,touched:b.touched,value:b.value};if(typeof GamepadButton!=='undefined')Object.setPrototypeOf(x,GamepadButton.prototype);return x;}),hapticActuators:pad.hapticActuators,vibrationActuator:pad.vibrationActuator,__ftcwSlot:pad.__ftcwSlot};if(typeof Gamepad!=='undefined')Object.setPrototypeOf(copy,Gamepad.prototype);return copy;}
  Navigator.prototype.getGamepads=function(){const real=Array.from(nativeGetGamepads.call(this));if(pads.size===0)return real;getCalls++;for(const pad of pads.values()){if(real[pad.index]!=null){const previous=snapshot(pad);previous.connected=false;assignIndex(pad);fire('gamepaddisconnected',previous);fire('gamepadconnected',pad);}}for(const pad of pads.values()){while(real.length<=pad.index)real.push(null);if(real[pad.index]===null||real[pad.index]===undefined)real[pad.index]=snapshot(pad);}return real;};
  Object.defineProperty(navigator,'__ftcwBridge',{value:{get pads(){return[...pads.values()];},get up(){return bridgeUp;},persona:PERSONA}});
})();
